// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetoMarcacoes.Data;

#nullable disable

namespace projetoMarcacoes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220605111446_primeira")]
    partial class primeira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("projetoMarcacoes.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tclientes");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tfuncionarios");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Funcionario_Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Tfuncionario_servico");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Marcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Funcionario_ServicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Funcionario_ServicoId");

                    b.ToTable("Tmarcacoes");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Custo")
                        .HasColumnType("float");

                    b.Property<double>("DuracaoHora")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tservicos");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Funcionario_Servico", b =>
                {
                    b.HasOne("projetoMarcacoes.Models.Funcionario", "Funcionario")
                        .WithMany("Funcionario_Servicos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetoMarcacoes.Models.Servico", "Servico")
                        .WithMany("Funcionario_Servicos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Marcacao", b =>
                {
                    b.HasOne("projetoMarcacoes.Models.Cliente", "Cliente")
                        .WithMany("Marcacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetoMarcacoes.Models.Funcionario_Servico", "Funcionario_Servico")
                        .WithMany()
                        .HasForeignKey("Funcionario_ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario_Servico");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Cliente", b =>
                {
                    b.Navigation("Marcacoes");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Funcionario", b =>
                {
                    b.Navigation("Funcionario_Servicos");
                });

            modelBuilder.Entity("projetoMarcacoes.Models.Servico", b =>
                {
                    b.Navigation("Funcionario_Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
